apiVersion: projectcalico.org/v3
kind: GlobalAlert
metadata:
  name: network.ssh-to-hipstershop
spec:
  description: "ssh flows to hipstershop namespace"
  summary: "[flows] ssh flow in hipstershop namespace detected from ${source_namespace}/${source_name_aggr}"
  severity: 100
  period: 10m
  lookback: 10m
  dataSet: flows
  query: proto='tcp' AND action='allow' AND dest_port='22' AND (source_namespace='hipstershop' OR dest_namespace='hipstershop') AND reporter=src
  aggregateBy: [source_namespace, source_name_aggr]
  field: num_flows
  metric: sum
  condition: gt
  threshold: 0
